 version: 2

 jobs:
  build:
    steps:
      - checkout
      - npm install
      - npm test
 workflows:
   version: 2
   build: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - build